# Generated by Django 4.2.4 on 2023-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_seller_id_item_seller_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
